### ISSUE TITLE
Could you clarify how to use the assistant and capture buttons?

### ISSUE THREAD

**Issue by omair94** [71/stadiacontroller#6]
Sorry, I'm not very familiar with using command line flags. Could you explain how to, say, bind capture to a keypress like F13? Or link to a tutorial? Thanks in advance.

**Comment by 71** [comment]
Hey there,

Unfortunately the only way to attach actions to these keys is to add command-line flags. If you, for instance, want to simulate an F13 keypress, your best shot is to use a software like [AutoHotkey](https://www.autohotkey.com/) and to make a script that just presses a key.

For instance, let's say you create a script named `PrintScreen.ahk` with content:

```ahk
Send {PrintScreen}
```

Then you can start `stadiacontroller.exe -capture-pressed A:\Path\To\PrintScreen.ahk` (or add `-capture-pressed A:\Path\To\PrintScreen.ahk` to the command line arguments to a shortcut you created) and pressing the capture button will run `PrintScreen.ahk`, which will in turn simulate a `PrintScreen` button click and capture a screenshot.
